name: Build UFTPD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: UFTPD build
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        make test
